# Generated by Django 5.0 on 2023-12-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='coverart',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='uri',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
